language: ruby
rvm:
  - 2.3
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - awesome_bot README.md --allow-redirect --white-list pentesterlab.com
  - danger
notifications:
  email: false
